name: Build APK

on:
  push:
    branches:
      - cambiosDani
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.5'
          channel: 'stable'
          cache: true

      - name: Restore debug keystore
        run: |
          mkdir -p ~/.android
          echo "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64 -d > ~/.android/debug.keystore
          if [ ! -s ~/.android/debug.keystore ]; then
            echo "ERROR: DEBUG_KEYSTORE_BASE64 vacío o mal codificado"
            exit 1
          fi

      - name: Create .env
        run: |
          cat > .env <<EOF
          BASE_URL=${{ secrets.BASE_URL }}
          GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID }}
          EOF
          echo "[.env creado]"

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: redime-app-debug-${{ github.sha }}
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 30
